/**
 * OKIT extension protocol — shared types between OKIT server and Chrome extension.
 *
 * Atomic-capability protocol: the extension exposes generic actions (exec, navigate,
 * network-capture, etc.) and the OKIT server orchestrates platform-specific flows
 * (zhipu, volcengine, minimax) by composing these atoms. Adding a new platform
 * only requires server-side changes — the extension never needs to know platform
 * specifics.
 *
 * Inspired by opencli's protocol.
 */

export type Action =
  | 'exec'
  | 'navigate'
  | 'tabs'
  | 'cookies'
  | 'screenshot'
  | 'focus-window'
  | 'close-window'
  | 'set-file-input'
  | 'insert-text'
  | 'network-capture-start'
  | 'network-capture-read'
  | 'clipboard-read'
  | 'cdp';

export interface Command {
  /** Unique request ID — generated by OKIT server, echoed by extension in Result */
  id: string;
  /** Action type — which atomic capability to invoke */
  action: Action;
  /** Target tab ID (omit for the active automation tab) */
  tabId?: number;
  /** JS code to evaluate in page context (exec action) */
  code?: string;
  /** Logical session key — OKIT is single-user, so this is always 'okit', but kept
   *  for forward compatibility and to match the opencli contract. */
  workspace?: string;
  /** URL to navigate to (navigate action) */
  url?: string;
  /** Sub-operation for tabs: list, new, close, select */
  op?: 'list' | 'new' | 'close' | 'select';
  /** Tab index for tabs select/close */
  index?: number;
  /** Cookie domain filter */
  domain?: string;
  /** Screenshot format: png (default) or jpeg */
  format?: 'png' | 'jpeg';
  /** JPEG quality (0-100), only for jpeg format */
  quality?: number;
  /** Whether to capture full page (not just viewport) */
  fullPage?: boolean;
  /** Local file paths for set-file-input action */
  files?: string[];
  /** CSS selector for file input element (set-file-input action) */
  selector?: string;
  /** Raw text payload for insert-text action */
  text?: string;
  /** URL substring filter pattern for network capture actions (pipe-separated) */
  pattern?: string;
  /** CDP method name for 'cdp' action (e.g. 'Accessibility.getFullAXTree') */
  cdpMethod?: string;
  /** CDP method params for 'cdp' action */
  cdpParams?: Record<string, unknown>;
  /** Keep the automation window open for a user login handoff */
  hold?: boolean;
  /** Regex the clipboard text must fully match before it can be returned. */
  clipboardPattern?: string;
  clipboardAllowSurrounding?: boolean;
}

export interface Result {
  /** Matching request ID */
  id: string;
  /** Whether the command succeeded */
  ok: boolean;
  /** Result data on success */
  data?: unknown;
  /** Error message on failure */
  error?: string;
}

// ─── Connection configuration ───────────────────────────────────────
// The OKIT server pins port 3780 and only climbs to 3781+ when 3780 is
// already taken by another process. The extension probes these ports in
// order and locks onto the first one that answers, so a fallback port no
// longer breaks the extension.

/** Default OKIT server port */
export const OKIT_PORT = 3780;
/** All ports the OKIT server may occupy (probed in order). */
export const OKIT_PORTS = [3780, 3781, 3782, 3783, 3784, 3785];
export const OKIT_HOST = 'localhost';
/** WebSocket endpoint for a given port — extension connects here for the command stream */
export const wsUrl = (port: number) => `ws://${OKIT_HOST}:${port}/ws/extension`;
/** Lightweight health-check endpoint — probed before each WebSocket attempt.
 *  This avoids ERR_CONNECTION_REFUSED noise in the extension console, since
 *  new WebSocket() failures are not catchable via try/catch. */
export const pingUrl = (port: number) => `http://${OKIT_HOST}:${port}/ping`;
/** One-time WS auth token endpoint for a given port. The server only answers
 *  (CORS) extension origins, so ordinary web pages can neither fetch a token
 *  nor use the WS command channel. */
export const tokenUrl = (port: number) => `http://${OKIT_HOST}:${port}/api/extension/token`;

/** Default-port URLs (kept for backwards compatibility). */
export const OKIT_WS_URL = wsUrl(OKIT_PORT);
export const OKIT_PING_URL = pingUrl(OKIT_PORT);
export const OKIT_TOKEN_URL = tokenUrl(OKIT_PORT);

// ─── Reconnect tuning ───────────────────────────────────────────────
/** Base reconnect delay for extension WebSocket (ms) */
export const WS_RECONNECT_BASE_DELAY = 2000;
/** Max reconnect delay (ms) — kept short since OKIT server is long-lived */
export const WS_RECONNECT_MAX_DELAY = 5000;
