/**
 * OKIT extension protocol — shared types between OKIT server and Chrome extension.
 *
 * Atomic-capability protocol: the extension exposes generic actions (exec, navigate,
 * network-capture, etc.) and the OKIT server orchestrates platform-specific flows
 * (zhipu, volcengine, minimax) by composing these atoms. Adding a new platform
 * only requires server-side changes — the extension never needs to know platform
 * specifics.
 *
 * Inspired by opencli's protocol.
 */

export type Action =
  | 'exec'
  | 'navigate'
  | 'tabs'
  | 'cookies'
  | 'screenshot'
  | 'close-window'
  | 'set-file-input'
  | 'insert-text'
  | 'network-capture-start'
  | 'network-capture-read'
  | 'cdp';

export interface Command {
  /** Unique request ID — generated by OKIT server, echoed by extension in Result */
  id: string;
  /** Action type — which atomic capability to invoke */
  action: Action;
  /** Target tab ID (omit for the active automation tab) */
  tabId?: number;
  /** JS code to evaluate in page context (exec action) */
  code?: string;
  /** Logical session key — OKIT is single-user, so this is always 'okit', but kept
   *  for forward compatibility and to match the opencli contract. */
  workspace?: string;
  /** URL to navigate to (navigate action) */
  url?: string;
  /** Sub-operation for tabs: list, new, close, select */
  op?: 'list' | 'new' | 'close' | 'select';
  /** Tab index for tabs select/close */
  index?: number;
  /** Cookie domain filter */
  domain?: string;
  /** Screenshot format: png (default) or jpeg */
  format?: 'png' | 'jpeg';
  /** JPEG quality (0-100), only for jpeg format */
  quality?: number;
  /** Whether to capture full page (not just viewport) */
  fullPage?: boolean;
  /** Local file paths for set-file-input action */
  files?: string[];
  /** CSS selector for file input element (set-file-input action) */
  selector?: string;
  /** Raw text payload for insert-text action */
  text?: string;
  /** URL substring filter pattern for network capture actions (pipe-separated) */
  pattern?: string;
  /** CDP method name for 'cdp' action (e.g. 'Accessibility.getFullAXTree') */
  cdpMethod?: string;
  /** CDP method params for 'cdp' action */
  cdpParams?: Record<string, unknown>;
}

export interface Result {
  /** Matching request ID */
  id: string;
  /** Whether the command succeeded */
  ok: boolean;
  /** Result data on success */
  data?: unknown;
  /** Error message on failure */
  error?: string;
}

// ─── Connection configuration ───────────────────────────────────────
// OKIT server runs on port 3780 (auto-increments to 3781, 3782... if taken).
// Phase 1 limitation: the extension hardcodes 3780. If the server is on a
// different port, the extension cannot connect. See docs/AUTO-CREATE-EXTENSION-PLAN.md.

/** Default OKIT server port */
export const OKIT_PORT = 3780;
export const OKIT_HOST = 'localhost';
/** WebSocket endpoint — extension connects here for command stream */
export const OKIT_WS_URL = `ws://${OKIT_HOST}:${OKIT_PORT}/ws/extension`;
/** Lightweight health-check endpoint — probed before each WebSocket attempt.
 *  This avoids ERR_CONNECTION_REFUSED noise in the extension console, since
 *  new WebSocket() failures are not catchable via try/catch. */
export const OKIT_PING_URL = `http://${OKIT_HOST}:${OKIT_PORT}/ping`;

// ─── Reconnect tuning ───────────────────────────────────────────────
/** Base reconnect delay for extension WebSocket (ms) */
export const WS_RECONNECT_BASE_DELAY = 2000;
/** Max reconnect delay (ms) — kept short since OKIT server is long-lived */
export const WS_RECONNECT_MAX_DELAY = 5000;
