import { Provider } from "./types";

export const PRESET_PROVIDERS: Omit<Provider, 'vaultKey'>[] = [
  {
    id: "anthropic",
    name: "Anthropic",
    type: "anthropic",
    baseUrl: "https://api.anthropic.com",
    authMode: "both",
    models: [
      { id: "claude-opus-4-7", name: "Claude Opus 4.7" },
      { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6" },
      { id: "claude-haiku-4-5", name: "Claude Haiku 4.5" },
    ],
  },
  {
    id: "openai",
    name: "OpenAI",
    type: "openai",
    baseUrl: "https://api.openai.com/v1",
    authMode: "api_key",
    models: [
      { id: "gpt-5.5", name: "GPT-5.5" },
      { id: "gpt-5.4-mini", name: "GPT-5.4 Mini" },
      { id: "o3", name: "O3" },
      { id: "o4-mini", name: "O4 Mini" },
      { id: "gpt-4.1", name: "GPT-4.1" },
    ],
  },
  {
    id: "openai-codex",
    name: "OpenAI Codex",
    type: "openai",
    baseUrl: "https://chatgpt.com/backend-api/codex",
    authMode: "oauth",
    models: [
      { id: "codex-1", name: "Codex 1" },
    ],
  },
  {
    id: "google",
    name: "Google Gemini",
    type: "google",
    baseUrl: "https://generativelanguage.googleapis.com",
    endpoints: [
      { type: "google", baseUrl: "https://generativelanguage.googleapis.com" },
      { type: "openai", baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai" },
    ],
    authMode: "api_key",
    models: [
      { id: "gemini-3", name: "Gemini 3" },
      { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro" },
      { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash" },
      { id: "gemini-2.5-flash-lite", name: "Gemini 2.5 Flash Lite" },
    ],
  },
  {
    id: "volcengine",
    name: "火山引擎",
    type: "openai",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    authMode: "api_key",
    models: [
      { id: "doubao-seed-2.0-pro", name: "Doubao Seed 2.0 Pro" },
      { id: "doubao-seed-1-8-251228", name: "Doubao Seed 1.8" },
      { id: "doubao-seed-code-preview-251028", name: "Doubao Seed Code" },
      { id: "doubao-1-5-pro-32k-250115", name: "Doubao 1.5 Pro 32K" },
      { id: "deepseek-v3.2", name: "DeepSeek V3.2" },
      { id: "glm-4.7", name: "GLM-4.7" },
      { id: "glm-5", name: "GLM-5" },
      { id: "kimi-k2.5", name: "Kimi K2.5" },
    ],
  },
  {
    id: "zai",
    name: "智谱 AI（国内站）",
    type: "openai",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    endpoints: [
      { type: "openai", baseUrl: "https://open.bigmodel.cn/api/paas/v4" },
      { type: "anthropic", baseUrl: "https://open.bigmodel.cn/api/anthropic" },
    ],
    authMode: "api_key",
    models: [
      { id: "glm-5.1", name: "GLM-5.1" },
      { id: "glm-5", name: "GLM-5" },
      { id: "glm-5-turbo", name: "GLM-5 Turbo" },
      { id: "glm-5v-turbo", name: "GLM-5V Turbo" },
      { id: "glm-4.7", name: "GLM-4.7" },
      { id: "glm-4.7-flash", name: "GLM-4.7 Flash" },
      { id: "glm-4.6", name: "GLM-4.6" },
      { id: "glm-ocr", name: "GLM OCR" },
    ],
  },
  {
    id: "zai-global",
    name: "Z.AI（国际站）",
    type: "openai",
    baseUrl: "https://api.z.ai/api/paas/v4",
    endpoints: [
      { type: "openai", baseUrl: "https://api.z.ai/api/paas/v4" },
      { type: "anthropic", baseUrl: "https://api.z.ai/api/anthropic" },
    ],
    authMode: "api_key",
    models: [
      { id: "glm-5.1", name: "GLM-5.1" },
      { id: "glm-5", name: "GLM-5" },
      { id: "glm-5-turbo", name: "GLM-5 Turbo" },
      { id: "glm-5v-turbo", name: "GLM-5V Turbo" },
      { id: "glm-4.7", name: "GLM-4.7" },
      { id: "glm-4.7-flash", name: "GLM-4.7 Flash" },
      { id: "glm-4.6", name: "GLM-4.6" },
      { id: "glm-ocr", name: "GLM OCR" },
    ],
  },
  {
    id: "minimax",
    name: "MiniMax（国内站）",
    type: "openai",
    baseUrl: "https://api.minimaxi.com/v1",
    authMode: "api_key",
    models: [
      { id: "MiniMax-M2.7", name: "MiniMax M2.7" },
      { id: "MiniMax-M2.5", name: "MiniMax M2.5" },
      { id: "MiniMax-M2", name: "MiniMax M2" },
      { id: "MiniMax-Text-01", name: "MiniMax Text 01" },
    ],
  },
  {
    id: "minimax-global",
    name: "MiniMax（国际站）",
    type: "openai",
    baseUrl: "https://api.minimax.io/v1",
    authMode: "api_key",
    models: [
      { id: "MiniMax-M2.7", name: "MiniMax M2.7" },
      { id: "MiniMax-M2.5", name: "MiniMax M2.5" },
      { id: "MiniMax-M2", name: "MiniMax M2" },
      { id: "MiniMax-Text-01", name: "MiniMax Text 01" },
    ],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    type: "openai",
    baseUrl: "https://api.deepseek.com",
    endpoints: [
      { type: "openai", baseUrl: "https://api.deepseek.com" },
      { type: "anthropic", baseUrl: "https://api.deepseek.com/anthropic" },
    ],
    authMode: "api_key",
    models: [
      { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
      { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
      { id: "deepseek-chat", name: "DeepSeek Chat (V4)" },
      { id: "deepseek-reasoner", name: "DeepSeek Reasoner (V4)" },
    ],
  },
  {
    id: "moonshot",
    name: "Moonshot (Kimi)",
    type: "openai",
    baseUrl: "https://api.moonshot.ai/v1",
    authMode: "api_key",
    models: [
      { id: "kimi-latest", name: "Kimi Latest" },
      { id: "moonshot-v1-128k", name: "Moonshot V1 128K" },
      { id: "moonshot-v1-32k", name: "Moonshot V1 32K" },
      { id: "moonshot-v1-8k", name: "Moonshot V1 8K" },
    ],
  },
  {
    id: "kimi-coding",
    name: "Kimi Coding",
    type: "openai",
    baseUrl: "https://api.kimi.com",
    authMode: "api_key",
    models: [
      { id: "kimi-k2.5", name: "Kimi K2.5" },
      { id: "kimi-k2-thinking", name: "Kimi K2 Thinking" },
      { id: "kimi-code", name: "Kimi Code" },
    ],
  },
  {
    id: "qwen",
    name: "通义千问 (Qwen)",
    type: "openai",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    authMode: "api_key",
    models: [
      { id: "qwen3.6-max-preview", name: "Qwen3.6 Max Preview" },
      { id: "qwen-max", name: "Qwen Max" },
      { id: "qwen-plus", name: "Qwen Plus" },
      { id: "qwen-turbo", name: "Qwen Turbo" },
      { id: "qwen3-235b", name: "Qwen3 235B" },
      { id: "qwen3-32b", name: "Qwen3 32B" },
    ],
  },
  {
    id: "qianfan",
    name: "百度千帆",
    type: "openai",
    baseUrl: "https://qianfan.baidubce.com/v2",
    endpoints: [
      { type: "openai", baseUrl: "https://qianfan.baidubce.com/v2" },
      { type: "openai", baseUrl: "https://qianfan.baidubce.com/v2/coding" },
    ],
    authMode: "api_key",
    models: [
      { id: "ernie-4.5-8k-preview", name: "ERNIE 4.5" },
      { id: "ernie-4.0-8k", name: "ERNIE 4.0" },
      { id: "deepseek-v3.2", name: "DeepSeek V3.2" },
    ],
  },
  {
    id: "xai",
    name: "xAI (Grok)",
    type: "openai",
    baseUrl: "https://api.x.ai/v1",
    authMode: "api_key",
    models: [
      { id: "grok-4.20-0309-reasoning", name: "Grok 4.20 Reasoning" },
      { id: "grok-4.20-0309-non-reasoning", name: "Grok 4.20" },
      { id: "grok-4-1-fast-reasoning", name: "Grok 4.1 Fast Reasoning" },
      { id: "grok-4-1-fast-non-reasoning", name: "Grok 4.1 Fast" },
    ],
  },
  {
    id: "mistral",
    name: "Mistral",
    type: "openai",
    baseUrl: "https://api.mistral.ai/v1",
    authMode: "api_key",
    models: [
      { id: "mistral-large-latest", name: "Mistral Large 3" },
      { id: "devstral-medium-latest", name: "Devstral Medium" },
      { id: "devstral-small-latest", name: "Devstral Small" },
      { id: "mistral-medium-latest", name: "Mistral Medium 3" },
      { id: "mistral-small-latest", name: "Mistral Small 3" },
    ],
  },
  {
    id: "stepfun",
    name: "阶跃星辰 (StepFun)",
    type: "openai",
    baseUrl: "https://api.stepfun.com/v1",
    authMode: "api_key",
    models: [
      { id: "step-3.5-flash", name: "Step 3.5 Flash" },
      { id: "step-2", name: "Step 2" },
      { id: "step-1-flash", name: "Step 1 Flash" },
    ],
  },
  {
    id: "xiaomi",
    name: "小米 MiMo",
    type: "openai",
    baseUrl: "https://api.xiaomimimo.com/v1",
    endpoints: [
      { type: "openai", baseUrl: "https://api.xiaomimimo.com/v1" },
      { type: "anthropic", baseUrl: "https://api.xiaomimimo.com/anthropic" },
    ],
    authMode: "api_key",
    models: [
      { id: "MiMo-V2-Pro", name: "MiMo V2 Pro" },
      { id: "MiMo-V2-Flash", name: "MiMo V2 Flash" },
    ],
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    type: "openai",
    baseUrl: "https://openrouter.ai/api/v1",
    authMode: "api_key",
    models: [
      { id: "anthropic/claude-opus-4-7", name: "Claude Opus 4.7" },
      { id: "openai/gpt-5.5", name: "GPT-5.5" },
      { id: "google/gemini-2.5-pro", name: "Gemini 2.5 Pro" },
      { id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    ],
  },
  {
    id: "groq",
    name: "Groq",
    type: "openai",
    baseUrl: "https://api.groq.com/openai/v1",
    authMode: "api_key",
    models: [
      { id: "gpt-oss", name: "GPT OSS" },
      { id: "kimi-k2", name: "Kimi K2" },
      { id: "qwen3-32b", name: "Qwen3 32B" },
      { id: "llama-3-groq-70b-tool-use", name: "Llama 3 70B Tool Use" },
    ],
  },
  {
    id: "fireworks",
    name: "Fireworks",
    type: "openai",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    authMode: "api_key",
    models: [
      { id: "accounts/fireworks/models/qwen3-235b", name: "Qwen3 235B" },
      { id: "accounts/fireworks/models/llama4-maverick", name: "Llama 4 Maverick" },
      { id: "accounts/fireworks/models/deepseek-r1", name: "DeepSeek R1" },
    ],
  },
  {
    id: "together",
    name: "Together AI",
    type: "openai",
    baseUrl: "https://api.together.xyz/v1",
    authMode: "api_key",
    models: [
      { id: "meta-llama/Llama-4-Maverick-17B-128E-Instruct", name: "Llama 4 Maverick" },
      { id: "deepseek-ai/DeepSeek-V4", name: "DeepSeek V4" },
      { id: "Qwen/Qwen3-235B-A22B", name: "Qwen3 235B" },
    ],
  },
  {
    id: "ollama",
    name: "Ollama (本地)",
    type: "openai",
    baseUrl: "http://127.0.0.1:11434/v1",
    authMode: "api_key",
    models: [],
  },
  {
    id: "litellm",
    name: "LiteLLM (本地)",
    type: "openai",
    baseUrl: "http://localhost:4000",
    authMode: "api_key",
    models: [],
  },
];
